export const TOGGLE_AUTHORS = "TOGGLE_AUTHORS";

export const REQUEST_CITES_PENDING = "REQUEST_CITES_PENDING";
export const REQUEST_CITES_SUCCESS = "REQUEST_CITES_SUCCESS";
export const REQUEST_CITES_FAIL = "REQUEST_CITES_FAIL";

export const REQUEST_AUTHORS_PENDING = "REQUEST_AUTHORS_PENDING";
export const REQUEST_AUTHORS_SUCCESS = "REQUEST_AUTHORS_SUCCESS";
export const REQUEST_AUTHORS_FAIL = "REQUEST_AUTHORS_FAIL";

export const REQUEST_CREATE_CITE_PENDING = "REQUEST_CREATE_CITE_PENDING";
export const REQUEST_CREATE_CITE_SUCCESS = "REQUEST_CREATE_CITE_SUCCESS";
export const REQUEST_CREATE_CITE_FAIL = "REQUEST_CREATE_CITE_FAIL";
