export const TOGGLE_AUTHORS = "TOGGLE_AUTHORS";

export const REQUEST_DATA_PENDING = "REQUEST_DATA_PENDING";
export const REQUEST_DATA_SUCCESS = "REQUEST_DATA_SUCCESS";
export const REQUEST_DATA_FAIL = "REQUEST_DATA_FAIL";
